import { type AssessmentSection } from "./questions";

export const PULSE_SECTIONS: AssessmentSection[] = [
  {
    key: "pulse-check",
    title: "Pulse Check",
    description: "A quick health check on your partnership since the last assessment.",
    questions: [
      {
        key: "overall-satisfaction",
        label: "How satisfied are you with the partnership right now?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "communication-quality",
        label: "How would you rate the quality of communication?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "trust-level",
        label: "How would you rate the current level of trust?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "alignment-direction",
        label: "How aligned are you on the direction of the venture?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "workload-fairness",
        label: "How fair does the workload distribution feel?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "decision-making-quality",
        label: "How effective has decision-making been?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "conflict-health",
        label: "How well have disagreements been handled?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "energy-motivation",
        label: "How energized and motivated do you feel about the venture?",
        type: "slider",
        required: true,
        min: 1,
        max: 10,
      },
      {
        key: "biggest-win",
        label: "What has been the biggest win since the last check-in?",
        type: "free-text",
        required: true,
        minLength: 30,
      },
      {
        key: "biggest-concern",
        label: "What is your biggest concern right now?",
        type: "free-text",
        required: true,
        minLength: 30,
      },
      {
        key: "scenario-current",
        label: "How would you handle this situation?",
        type: "scenario",
        required: true,
        scenarios: [
          "You and your partner disagree on whether to hire the next team member or invest in marketing",
          "Your partner suggests a major pivot that you're unsure about",
        ],
      },
    ],
  },
];
